name: Prerelease build
on:
  push:
    branches:
      - Alpha
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/prerelease.yml'
  pull_request:
    branches:
      - Alpha

jobs:
  Build:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          # WithoutCGO
          - { type: "WithoutCGO", target: "linux-amd64 linux-amd64-compatible", id: "1" }
          - { type: "WithoutCGO", target: "linux-armv5 linux-armv6 linux-armv7 linux-arm64", id: "2" }
          - { type: "WithoutCGO", target: "linux-mips64 linux-mips64le", id: "3" }
          - { type: "WithoutCGO", target: "linux-mips-softfloat linux-mips-hardfloat linux-mipsle-softfloat linux-mipsle-hardfloat", id: "4" }
          # - { type: "WithoutCGO", target: "freebsd-386 freebsd-amd64 freebsd-arm64", id: "5" }
          - { type: "WithoutCGO", target: "windows-amd64-compatible windows-amd64 windows-386", id: "6" }
          - { type: "WithoutCGO", target: "windows-arm64 windows-arm32v7", id: "7" }
          # - { type: "WithoutCGO", target: "darwin-amd64 darwin-arm64", id: "8" }
          - { type: "WithoutCGO", target: "android-arm64", id: "9" }
          # WithCGO
          # - { type: "WithCGO", target: "windows/*", id: "1" }
          # - { type: "WithCGO", target: "linux/386,linux/amd64", id: "2" }
          # - { type: "WithCGO", target: "linux/arm64,linux/riscv64", id: "3" }
          # - { type: "WithCGO", target: "linux/arm,linux/arm-6,linux/arm-7", id: "4" }
          # - { type: "WithCGO", target: "linux/mips,linux/mipsle", id: "5" }
          # - { type: "WithCGO", target: "linux/mips64,linux/mips64le", id: "6" }
          # - { type: "WithCGO", target: "darwin-10.16/*", id: "7" }
          - { type: "WithCGO", target: "android", id: "8" }

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set variables
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        shell: bash

      - name: Set variables
        if: ${{github.ref_name=='Alpha'}}
        run: echo "VERSION=alpha-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        shell: bash

      # - name: Set variables
        # if: ${{github.ref_name=='Beta'}}
        # run: echo "VERSION=beta-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        # shell: bash

      - name: Set variables
        if: ${{github.ref_name==''}}
        run: echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
        shell: bash

      - name: Set ENV
        run: |
          echo "NAME=clash.meta" >> $GITHUB_ENV
          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
          echo "ShortSHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
          echo "BUILDTIME=$(TZ=Asia/Jakarta date)" >> $GITHUB_ENV
        shell: bash

      - name: Set ENV
        run: |
          echo "TAGS=with_gvisor,with_lwip" >> $GITHUB_ENV
          echo "LDFLAGS=-X 'github.com/Dreamacro/clash/constant.Version=${VERSION}' -X 'github.com/Dreamacro/clash/constant.BuildTime=${BUILDTIME}' -w -s -buildid=" >> $GITHUB_ENV
        shell: bash

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true

      # - name: Test
        # if: ${{ github.ref_name=='Beta' && matrix.job.id=='1' && matrix.job.type=='WithoutCGO' }}
        # run: |
          # go test ./...

      - name: Build WithoutCGO
        if: ${{ matrix.job.type=='WithoutCGO' }}
        env:
          NAME: Clash.Meta
          BINDIR: bin
        run: make -j$(($(nproc) + 1)) ${{ matrix.job.target }}

      - uses: nttld/setup-ndk@v1
        if: ${{ matrix.job.type=='WithCGO' && matrix.job.target=='android' }}
        id: setup-ndk
        with:
          ndk-version: r25b
          add-to-path: false
          local-cache: true

      - name: Build Android
        if: ${{ matrix.job.type=='WithCGO' && matrix.job.target=='android' }}
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          mkdir bin
          CC=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin
          CGO_ENABLED=1 CC=${CC}/aarch64-linux-android33-clang GOARCH=arm64 GOOS=android go build -tags ${TAGS} -trimpath -ldflags "${LDFLAGS}" -o bin/${NAME}-android-arm64
          CGO_ENABLED=1 CC=${CC}/armv7a-linux-androideabi33-clang GOARCH=arm GOOS=android GOARM=7 go build -tags ${TAGS} -trimpath -ldflags "${LDFLAGS}" -o bin/${NAME}-android-armv7
          CGO_ENABLED=1 CC=${CC}/i686-linux-android33-clang GOARCH=386 GOOS=android go build -tags ${TAGS} -trimpath -ldflags "${LDFLAGS}" -o bin/${NAME}-android-x86
          CGO_ENABLED=1 CC=${CC}/x86_64-linux-android33-clang GOARCH=amd64 GOOS=android go build -tags ${TAGS} -trimpath -ldflags "${LDFLAGS}" -o bin/${NAME}-android-x64

      - name: Set up xgo
        if: ${{ matrix.job.type=='WithCGO' && matrix.job.target!='android' }}
        run: |
          docker pull techknowlogick/xgo:latest
          go install src.techknowlogick.com/xgo@latest

      - name: Build by xgo
        if: ${{ matrix.job.type=='WithCGO' && matrix.job.target!='android' }}
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          mkdir bin
          xgo --branch ${{ github.ref_name }} --targets="${{ matrix.job.target }}" --tags="${TAGS}" -ldflags="${LDFLAGS}" --out bin/${NAME} github.com/${{ github.repository }}

      - name: Rename
        if: ${{ matrix.job.type=='WithCGO' }}
        run: |
          cd bin
          ls -la
          cp ../.github/rename-cgo.sh ./
          bash ./rename-cgo.sh
          rm ./rename-cgo.sh
          ls -la
          cd ..

      - name: Zip
        if: ${{  success() }}
        run: |
          cd bin
          ls -la
          chmod +x *
          cp ../.github/release.sh ./
          bash ./release.sh
          rm ./release.sh
          ls -la
          cd ..

      - uses: actions/upload-artifact@v3
        if: ${{  success() }}
        with:
          name: artifact
          path: bin/


  Upload:
    permissions: write-all
    needs: [ Build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: bin/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: bin

      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: Prerelease-${{ github.ref_name }}
          deleteOnlyFromDrafts: false

      - name: Tag Repo
        uses: richardsimko/update-tag@v1.0.6
        with:
          tag_name: Prerelease-${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Alpha
        uses: softprops/action-gh-release@v1
        if: ${{  success() }}
        with:
          tag: ${{ github.ref_name }}
          tag_name: Prerelease-${{ github.ref_name }}
          files: bin/*
          prerelease: true
          generate_release_notes: true

  telegram:
    name: telegram Upload Release
    runs-on: ubuntu-latest
    needs: Upload
    steps:
      - name: Donwload Artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: artifacts
      - name: Release
        run: |
          mkdir upload
          find artifacts -name "*.gz" -exec cp {} upload \;
          
          function upload() {
            for gz in $@; do
              echo ">> Uploading $gz"
              curl https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument \
                -X POST \
                -F chat_id="${{ secrets.TELEGRAM_CHANNEL }}" \
                -F document="@$gz" \
                --silent --show-error --fail >/dev/null &
            done
            for job in $(jobs -p); do
              wait $job || exit 1
            done
          }
          upload upload/*